version: "2"

services:
  api:
    image: orvice/monitor-server
    restart: always
    volumes:
      - ./log:/app/log
      - ./config:/etc/monitor-server
    ports:
      - 82:8081
    environment:
      - NODE_CONFIG_PATH=/etc/monitor-server/config.json
      - LISTEN_ADDR=:8081
      - POST_KEY=key
    container_name: monitor-server

  ui:
    image: orvice/monitor-ui
    restart: always
    volumes:
      - ./log:/var/log/nginx
    ports:
      - 81:80
    environment:
      - API_URI=http://domain.com:82
      - APP_NAME=BlackCat
    container_name: monitor-ui
